---
- name: ACME clients setup
  become: true
  become_user: root
  block:
    - name: EPEL repo present
      when: ansible_pkg_mgr == 'dnf'
      ansible.builtin.package:
        name: epel-release
        state: present

    - name: Certbot present
      ansible.builtin.package:
        name:
          - certbot
        state: present
