---
- name: ACME clients setup
  become: yes
  become_user: root
  block:
    - name: EPEL repo present
      when: ansible_pkg_mgr == 'dnf'
      package:
        name: epel-release
        state: present

    - name: Certbot present
      package:
        name:
          - certbot
        state: present
