---
os: linux
dist: focal
language: python

services:
  - docker

env:
  global:
    - ANSIBLE_PIPELINING=yes
    - ANSIBLE_FORKS=16

install:
  - python3 -m pip install ansible ansible-lint yamllint 'molecule[docker]' flake8

script:
  - molecule --version
  - ansible --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
