---
dist: xenial

language: python

services:
  - docker

env:
  global:
    - ANSIBLE_PIPELINING=yes
    - ANSIBLE_FORKS=16

install:
  - pip install 'molecule[docker]>=2.22rc1' docker flake8

script:
  - molecule --version
  - ansible --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
