---
os: linux
dist: focal
language: python

services:
  - docker

cache: pip

env:
  global:
    - ANSIBLE_PIPELINING=yes
    - ANSIBLE_FORKS=16

install:
  - python3 -m pip install ansible ansible-lint yamllint 'molecule[docker]' flake8 pytest-testinfra

script:
  - molecule --version
  - ansible --version
  - yamllint .
  - ansible-lint -v .
  - flake8
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
