- become: yes
  become_user: root
  block:
    - name: Curl installed
      package:
        name: curl

    - name: Certhub challenge test server hook script installed
      loop:
        - certbot-hooks/testsrv-dns-01-auth
        - certbot-hooks/testsrv-dns-01-cleanup
      copy:
        src: "files/{{ item }}"
        dest: "/usr/local/lib/certhub/{{ item }}"
        owner: root
        group: root
        mode: 0755
