- name: Pebble CA setup
  become: yes
  become_user: root
  block:
    - when: ansible_pkg_mgr == 'apt'
      set_fact:
        crt_dest: /usr/local/share/ca-certificates/pebble-ca.crt
        crt_update_cmd: >
          update-ca-certificates

    - when: ansible_pkg_mgr == 'yum'
      set_fact:
        crt_dest: /etc/pki/ca-trust/source/anchors/pebble-ca.crt
        crt_update_cmd: >
          update-ca-trust extract

    - name: Pebble CA downloaded
      register: pebble_ca_download
      get_url:
        dest: "{{ crt_dest }}"
        url: https://raw.githubusercontent.com/letsencrypt/pebble/v2.0.2/test/certs/pebble.minica.pem
        checksum: sha256:ba84a61eedf42e2704520116af71cc53ead0e861f32cb93ea8fc5cca5ca5cc29

    - name: Pebble CA installed
      when: pebble_ca_download is changed
      command: >
        {{ crt_update_cmd }}
