---
- name: Pebble CA setup
  become: yes
  become_user: root
  block:
    - name: CA Locations and Commands on Debian/Ubuntu detected
      when: ansible_pkg_mgr == 'apt'
      set_fact:
        crt_dest: /usr/local/share/ca-certificates/pebble-ca.crt
        crt_update_cmd: >
          update-ca-certificates

    - name: CA Locations and Commands on Centos detected
      when: ansible_pkg_mgr == 'yum'
      set_fact:
        crt_dest: /etc/pki/ca-trust/source/anchors/pebble-ca.crt
        crt_update_cmd: >
          update-ca-trust extract

    - name: Pebble CA present
      register: pebble_ca_copy
      copy:
        dest: "{{ crt_dest }}"
        src: pebble.minica.pem

    - name: Pebble CA installed
      when: pebble_ca_copy is changed
      command: >
        {{ crt_update_cmd }}
