---
- name: Certbot run / Cert expiry path and timer units enabled and started
  become: yes
  become_user: root
  loop:
    - "{{ certhub_cert_expiry_path_unit }}"
    - "{{ certhub_cert_expiry_timer_unit }}"
    - "{{ certhub_certbot_run_path_unit }}"
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
