---
- name: Certificate export and reload units configured
  become: yes
  become_user: root
  block:
    - name: Certificate export path unit enabled and started
      systemd:
        name: "certhub-cert-export@{{ certhub_cert_slug }}.path"
        enabled: yes
        state: started

    - name: Certificate services reload present
      copy:
        content: "{{ certhub_cert_services | join('\n') }}"
        dest: "/etc/certhub/{{ certhub_cert_slug }}.services-reload.txt"
        owner: root
        group: root
        mode: 0644

    - name: Certificate service reload path units enabled and started
      when: certhub_cert_services | length > 0
      systemd:
        name: "certhub-cert-reload@{{ certhub_cert_slug }}.path"
        enabled: yes
        state: started

    - name: Certificate service reload path unit stopped and disabled
      when: certhub_cert_services | length == 0
      systemd:
        name: "certhub-cert-reload@{{ certhub_cert_slug }}.path"
        enabled: no
        state: stopped
