---
- name: Certificate export, send and reload units configured
  become: yes
  become_user: root
  block:
    - name: Certificate export path unit enabled and started
      systemd:
        name: "{{ certhub_cert_export_path_unit }}"
        enabled: yes
        state: started

    - name: Certificate services reload present
      copy:
        content: "{{ certhub_cert_services | join('\n') }}"
        dest: "{{ certhub_cert_reload_config_path }}"
        owner: root
        group: root
        mode: 0644

    - name: Certificate service reload path units enabled and started
      when: certhub_cert_services | length > 0
      systemd:
        name: "{{ certhub_cert_reload_path_unit }}"
        enabled: yes
        state: started

    - name: Certificate service reload path unit stopped and disabled
      when: certhub_cert_services | length == 0
      systemd:
        name: "{{ certhub_cert_reload_path_unit }}"
        enabled: no
        state: stopped

    - name: Certificate send destinations present
      copy:
        content: "{{ certhub_cert_destinations | join('\n') }}"
        dest: "{{ certhub_cert_send_config_path }}"
        owner: root
        group: root
        mode: 0644

    - name: Certificate send path units enabled and started
      when: certhub_cert_destinations | length > 0
      systemd:
        name: "{{ certhub_cert_send_path_unit }}"
        enabled: yes
        state: started

    - name: Certificate send path unit stopped and disabled
      when: certhub_cert_destinations | length == 0
      systemd:
        name: "{{ certhub_cert_send_path_unit }}"
        enabled: no
        state: stopped
