---
- name: Certhub system setup
  become: true
  become_user: root
  block:
    - name: Certhub group present
      ansible.builtin.group:
        name: "{{ certhub_user_group }}"
        state: present
        system: true

    - name: Certhub user present
      ansible.builtin.user:
        name: "{{ certhub_user_name }}"
        group: "{{ certhub_user_group }}"
        state: present
        system: true
        home: "{{ certhub_home_dir_path }}"
        shell: /usr/bin/git-shell

    - name: Certhub home permissions
      ansible.builtin.file:
        path: "{{ certhub_home_dir_path }}"
        state: directory
        mode: "{{ certhub_home_dir_mode }}"

    - name: Certhub config directory present
      ansible.builtin.file:
        path: "{{ certhub_config_dir_path }}"
        state: directory
        owner: "{{ certhub_config_dir_owner }}"
        group: "{{ certhub_config_dir_group }}"
        mode: "{{ certhub_config_dir_mode }}"

    - name: Certhub status directory present
      ansible.builtin.file:
        path: "{{ certhub_status_dir_path }}"
        state: directory
        owner: "{{ certhub_status_dir_owner }}"
        group: "{{ certhub_status_dir_group }}"
        mode: "{{ certhub_status_dir_mode }}"

    - name: Certhub local certs directory present
      ansible.builtin.file:
        path: "{{ certhub_certs_dir_path }}"
        state: directory
        owner: "{{ certhub_certs_dir_owner }}"
        group: "{{ certhub_certs_dir_group }}"
        mode: "{{ certhub_certs_dir_mode }}"

    - name: Certhub local private directory present
      ansible.builtin.file:
        path: "{{ certhub_private_dir_path }}"
        state: directory
        owner: "{{ certhub_private_dir_owner }}"
        group: "{{ certhub_private_dir_group }}"
        mode: "{{ certhub_private_dir_mode }}"
