---
- name: Repo push units configured
  become: true
  become_user: root
  block:
    - name: Repo push path unit enabled and started
      ansible.builtin.systemd:
        name: "{{ certhub_repo_push_path_unit }}"
        enabled: true
        state: started
