---
- name: Test hooks
  become: true
  become_user: root
  block:
    - name: Curl installed
      ansible.builtin.package:
        name: "{{ 'curl-minimal' if ansible_pkg_mgr == 'dnf' else 'curl' }}"

    - name: Certhub challenge test server directories present
      loop:
        - certbot-hooks
        - lego-hooks
      ansible.builtin.file:
        state: directory
        dest: /usr/local/lib/certhub/{{ item }}
        owner: root
        group: root
        mode: "0755"

    - name: Certhub challenge test server hook script installed
      loop:
        - certbot-hooks/testsrv-dns-01-auth
        - certbot-hooks/testsrv-dns-01-cleanup
        - lego-hooks/testsrv-dns-01-auth
      ansible.builtin.copy:
        src: files/{{ item }}
        dest: /usr/local/lib/certhub/{{ item }}
        owner: root
        group: root
        mode: "0755"
