---
- become: yes
  become_user: root
  block:
    - name: Curl installed
      when: ansible_distribution != 'CentOS'
      package:
        name: curl

    - name: Certhub challenge test server directories present
      loop:
        - certbot-hooks
        - lego-hooks
      file:
        state: directory
        dest: "/usr/local/lib/certhub/{{ item }}"
        owner: root
        group: root
        mode: 0755

    - name: Certhub challenge test server hook script installed
      loop:
        - certbot-hooks/testsrv-dns-01-auth
        - certbot-hooks/testsrv-dns-01-cleanup
        - lego-hooks/testsrv-dns-01-auth
      copy:
        src: "files/{{ item }}"
        dest: "/usr/local/lib/certhub/{{ item }}"
        owner: root
        group: root
        mode: 0755
