---
- name: Update package index
  hosts: controller:server
  tasks:
    - name: Package index up to date
      become: true
      become_user: root
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

- name: General Setup
  hosts: controller:server
  tasks:
    - name: Git and OpenSSL present
      become: true
      become_user: root
      ansible.builtin.package:
        name:
          - acl
          - git
          - openssl
          - rsync
        state: present

    - name: Sudo Secure Path
      ansible.builtin.import_role:
        name: sudo_secure_path

    - name: Certhub
      ansible.builtin.import_role:
        name: znerol.certhub

- name: Controller Setup
  hosts: controller
  tasks:
    - name: Certbot
      ansible.builtin.import_role:
        name: certbot

    - name: Lego
      ansible.builtin.import_role:
        name: lego

    - name: Pebble CA
      ansible.builtin.import_role:
        name: pebble_ca

    - name: Test Hooks
      ansible.builtin.import_role:
        name: testsrv_hooks

    - name: Certbot No Root Config
      ansible.builtin.import_role:
        name: znerol.certhub
        tasks_from: certbot-noroot-config.yml

- name: Server Setup
  hosts: server
  tasks:
    - name: SSH Server
      ansible.builtin.import_role:
        name: sshserver

    - name: Regather facts
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop:
        - "{{ inventory_hostname }}"
        - "{{ molecule_certhub_controller }}"
      ansible.builtin.setup:

    - name: SSH Key Based Authentication
      vars:
        ssh_kba_client_hostname: "{{ molecule_certhub_controller }}"
        ssh_kba_client_user: certhub
        ssh_kba_server_user: certhub
      ansible.builtin.import_role:
        name: znerol.ssh_kba

    - name: TLS Server (Certbot)
      vars:
        tlsserver_cert_slug: "{{ inventory_hostname }}"
      ansible.builtin.import_role:
        name: tlsserver

    - name: TLS Server (Lego)
      vars:
        tlsserver_cert_slug: "{{ inventory_hostname }}-lego-test.ci.certhub.io"
      ansible.builtin.import_role:
        name: tlsserver

    - name: Repo push units setup
      delegate_to: "{{ molecule_certhub_controller }}"
      ansible.builtin.import_role:
        name: znerol.certhub
        tasks_from: repo-push-units.yml

- name: Certificate Configs
  hosts: server
  tasks:
    - name: Certbot service cert setup
      vars:
        certhub_cert_slug: "{{ inventory_hostname }}"
        certhub_cert_services:
          - nginx
      ansible.builtin.import_role:
        name: znerol.certhub
        tasks_from: cert-export-units.yml

    - name: Certbot controller cert setup
      delegate_to: "{{ molecule_certhub_controller }}"
      vars:
        certhub_cert_slug: "{{ inventory_hostname }}"
      block:
        - name: Certbot run units setup
          ansible.builtin.import_role:
            name: znerol.certhub
            tasks_from: certbot-run-units.yml

        - name: Certbot config installed
          become: true
          become_user: root
          ansible.builtin.copy:
            dest: "{{ certhub_certbot_config_path }}"
            owner: root
            group: root
            mode: "0644"
            content: |
              server=https://pebble:14000/dir
              agree-tos=true
              register-unsafely-without-email=true
              manual-public-ip-logging-ok=true
              preferred-challenges=dns
              manual=true
              manual-auth-hook=/usr/local/lib/certhub/certbot-hooks/testsrv-dns-01-auth
              manual-cleanup-hook=/usr/local/lib/certhub/certbot-hooks/testsrv-dns-01-cleanup

        - name: Certbot unit environment configured
          become: true
          become_user: root
          vars:
            certhub_unit_prefix: certhub-certbot-run
          ansible.builtin.copy:
            dest: "{{ certhub_cert_unit_env_path }}"
            owner: "{{ certhub_env_owner }}"
            group: "{{ certhub_env_group }}"
            mode: "{{ certhub_env_mode }}"
            content: |
              TESTSRV_BASE_URL=http://challtestsrv:8055/

    - name: Lego service cert setup
      vars:
        certhub_cert_slug: "{{ inventory_hostname }}-lego-test.ci.certhub.io"
        certhub_cert_services:
          - nginx
      ansible.builtin.import_role:
        name: znerol.certhub
        tasks_from: cert-export-units.yml

    - name: Lego controller cert setup
      delegate_to: "{{ molecule_certhub_controller }}"
      vars:
        certhub_cert_slug: "{{ inventory_hostname }}-lego-test.ci.certhub.io"
      block:
        - name: Lego run units setup
          ansible.builtin.import_role:
            name: znerol.certhub
            tasks_from: lego-run-units.yml

        - name: Lego unit environment configured
          become: true
          become_user: root
          vars:
            certhub_unit_prefix: certhub-lego-run
          ansible.builtin.copy:
            dest: "{{ certhub_cert_unit_env_path }}"
            owner: "{{ certhub_env_owner }}"
            group: "{{ certhub_env_group }}"
            mode: "{{ certhub_env_mode }}"
            content: |
              # Global args
              CERTHUB_LEGO_ARGS=\
                  --accept-tos \
                  --email travis-ci@certhub.io \
                  --server https://pebble:14000/dir \
                  --dns.disable-cp

              # Challenge args
              CERTHUB_LEGO_CHALLENGE_ARGS=--dns exec
              EXEC_PATH=/usr/local/lib/certhub/lego-hooks/testsrv-dns-01-auth
              TESTSRV_BASE_URL=http://challtestsrv:8055/
