# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python sudo python-devel python*-dnf bash && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python sudo bash python-xml && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python sudo bash ca-certificates && xbps-remove -O; fi

# Systemd additions

ENV container docker

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y systemd && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install systemd && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y systemd && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y systemd && zypper clean -a; \
    elif [ $(command -v apk) ]; then echo "Alpine Linux does not support systemd" >&2 && exit 1; \
    elif [ $(command -v xbps-install) ]; then echo "Void Linux does not support systemd" >&2 && exit 1; fi

# Install systemd-sysv on Debian and recent Ubuntu.
RUN if [ $(command -v apt-cache) ] && apt-cache show systemd-sysv >/dev/null 2>&1; then apt-get update && apt-get install -y systemd-sysv && apt-get clean; fi

# Don't start any optional services except for the few we need.
RUN find /etc/systemd/system \
    /lib/systemd/system \
    -path '*.wants/*' \
    -not -name '*journald*' \
    -not -name '*systemd-tmpfiles*' \
    -not -name '*systemd-user-sessions*' \
    -exec rm \{} \;

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y dbus && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install dbus && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y dbus && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y dbus && zypper clean -a; \
    elif [ $(command -v apk) ]; then echo "Alpine Linux does not support systemd" >&2 && exit 1; \
    elif [ $(command -v xbps-install) ]; then echo "Void Linux does not support systemd" >&2 && exit 1; fi

RUN systemctl set-default multi-user.target && \
    mkdir -p /etc/systemd/journald.conf.d && \
    echo "[Journal]" > /etc/systemd/journald.conf.d/forward-to-console.conf && \
    echo "ForwardToConsole=yes" >> /etc/systemd/journald.conf.d/forward-to-console.conf

STOPSIGNAL SIGRTMIN+3

CMD ["/sbin/init", "--log-target=journal"]
