---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: debian-node
    image: docker.io/znerolmolecule/molecule-prebuilt:debian-systemd
    pre_build_image: true
    override_command: no
    tty: yes
    systemd: always
    network: molecule-certhub
    extra_opts:
      - '--network-alias=debian-node-lego-test.ci.certhub.io'
    groups:
      - server
    volumes:
      - ansible-tmp.debian-node:/var/cache/ansible-tmp

  - name: ubuntu-node
    image: docker.io/znerolmolecule/molecule-prebuilt:ubuntu-systemd
    pre_build_image: true
    override_command: no
    tty: yes
    systemd: always
    network: molecule-certhub
    extra_opts:
      - '--network-alias=ubuntu-node-lego-test.ci.certhub.io'
    groups:
      - server
    volumes:
      - ansible-tmp.ubuntu-node:/var/cache/ansible-tmp

  - name: centos-node
    image: docker.io/znerolmolecule/molecule-prebuilt:centos-systemd
    pre_build_image: true
    override_command: no
    tty: yes
    systemd: always
    network: molecule-certhub
    extra_opts:
      - '--network-alias=centos-node-lego-test.ci.certhub.io'
    groups:
      - server
    volumes:
      - ansible-tmp.centos-node:/var/cache/ansible-tmp

  - name: debian-controller
    image: docker.io/znerolmolecule/molecule-prebuilt:debian-systemd
    pre_build_image: true
    override_command: no
    tty: yes
    systemd: always
    network: molecule-certhub
    groups:
      - controller
    volumes:
      - ansible-tmp.debian-controller:/var/cache/ansible-tmp

  - name: ubuntu-controller
    image: docker.io/znerolmolecule/molecule-prebuilt:ubuntu-systemd
    pre_build_image: true
    override_command: no
    tty: yes
    systemd: always
    network: molecule-certhub
    groups:
      - controller
    volumes:
      - ansible-tmp.ubuntu-controller:/var/cache/ansible-tmp

  - name: centos-controller
    image: docker.io/znerolmolecule/molecule-prebuilt:centos-systemd
    pre_build_image: true
    override_command: no
    tty: yes
    systemd: always
    network: molecule-certhub
    groups:
      - controller
    volumes:
      - ansible-tmp.centos-controller:/var/cache/ansible-tmp

  - name: challtestsrv
    image: docker.io/letsencrypt/pebble-challtestsrv
    pre_build_image: true
    command: /usr/bin/pebble-challtestsrv
    network: molecule-certhub
    volumes:
      - ansible-tmp.challtestsrv:/var/cache/ansible-tmp

  - name: pebble
    image: docker.io/letsencrypt/pebble:v1.0.1
    pre_build_image: true
    command: >
        /bin/sh -c
        "
        NSENTRY=$$(getent hosts challtestsrv) &&
        exec /usr/bin/pebble
        -config /test/config/pebble-config.json
        -dnsserver $${NSENTRY%% *}:8053
        "
    network: molecule-certhub
    volumes:
      - ansible-tmp.pebble:/var/cache/ansible-tmp

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /var/cache/ansible-tmp
  inventory:
    host_vars:
      debian-node:
        molecule_certhub_controller: debian-controller
      ubuntu-node:
        molecule_certhub_controller: ubuntu-controller
      centos-node:
        molecule_certhub_controller: centos-controller

verifier:
  name: testinfra
