---
dependency:
  name: galaxy

driver:
  name: podman

scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    #- cleanup
    #- destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    #- cleanup
    #- destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy

platforms:
  - name: debian-node
    image: docker.io/znerolmolecule/molecule-prebuilt:debian-systemd
    rootless: false
    pre_build_image: true
    override_command: no
    tty: yes
    systemd: always
    network: molecule-certhub
    extra_opts:
      - '--network-alias=debian-node-lego-test.ci.certhub.io'
    groups:
      - server

  - name: ubuntu-node
    image: docker.io/znerolmolecule/molecule-prebuilt:ubuntu-systemd
    rootless: false
    pre_build_image: true
    override_command: no
    tty: yes
    systemd: always
    network: molecule-certhub
    extra_opts:
      - '--network-alias=ubuntu-node-lego-test.ci.certhub.io'
    groups:
      - server

  - name: centos-node
    image: docker.io/znerolmolecule/molecule-prebuilt:centos-systemd
    rootless: false
    pre_build_image: true
    override_command: no
    tty: yes
    systemd: always
    network: molecule-certhub
    extra_opts:
      - '--network-alias=centos-node-lego-test.ci.certhub.io'
    groups:
      - server

  - name: debian-controller
    image: docker.io/znerolmolecule/molecule-prebuilt:debian-systemd
    rootless: false
    pre_build_image: true
    override_command: no
    tty: yes
    systemd: always
    network: molecule-certhub
    groups:
      - controller

  - name: ubuntu-controller
    image: docker.io/znerolmolecule/molecule-prebuilt:ubuntu-systemd
    rootless: false
    pre_build_image: true
    override_command: no
    tty: yes
    systemd: always
    network: molecule-certhub
    groups:
      - controller

  - name: centos-controller
    image: docker.io/znerolmolecule/molecule-prebuilt:centos-systemd
    rootless: false
    pre_build_image: true
    override_command: no
    tty: yes
    systemd: always
    network: molecule-certhub
    groups:
      - controller

  - name: challtestsrv
    image: docker.io/letsencrypt/pebble-challtestsrv
    rootless: false
    pre_build_image: true
    command: /usr/bin/pebble-challtestsrv
    network: molecule-certhub

  - name: pebble
    image: docker.io/letsencrypt/pebble:v1.0.1
    rootless: false
    pre_build_image: true
    command: >
        /bin/sh -c
        "
        NSENTRY=$$(getent hosts challtestsrv) &&
        exec /usr/bin/pebble
        -config /test/config/pebble-config.json
        -dnsserver $${NSENTRY%% *}:8053
        "
    network: molecule-certhub

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  inventory:
    host_vars:
      debian-node:
        molecule_certhub_controller: debian-controller
      ubuntu-node:
        molecule_certhub_controller: ubuntu-controller
      centos-node:
        molecule_certhub_controller: centos-controller

verifier:
  name: testinfra
