---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: debian-node
    image: znerolmolecule/molecule-prebuilt:debian-systemd
    override_command: no
    tty: yes
    capabilities:
      - SYS_ADMIN
    networks:
      - name: molecule-certhub
        aliases:
          - debian-node-lego-test.ci.certhub.io
    groups:
      - server
    security_opts:
      - seccomp=unconfined
    stop-signal: SIGRTMIN+3
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: ubuntu-node
    image: znerolmolecule/molecule-prebuilt:ubuntu-systemd
    override_command: no
    tty: yes
    capabilities:
      - SYS_ADMIN
    networks:
      - name: molecule-certhub
        aliases:
          - ubuntu-node-lego-test.ci.certhub.io
    groups:
      - server
    security_opts:
      - seccomp=unconfined
    stop-signal: SIGRTMIN+3
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: centos-node
    image: znerolmolecule/molecule-prebuilt:centos-systemd
    override_command: no
    tty: yes
    capabilities:
      - SYS_ADMIN
    networks:
      - name: molecule-certhub
        aliases:
          - centos-node-lego-test.ci.certhub.io
    groups:
      - server
    security_opts:
      - seccomp=unconfined
    stop-signal: SIGRTMIN+3
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: debian-controller
    image: znerolmolecule/molecule-prebuilt:debian-systemd
    override_command: no
    tty: yes
    capabilities:
      - SYS_ADMIN
    networks:
      - name: molecule-certhub
    groups:
      - controller
    security_opts:
      - seccomp=unconfined
    stop-signal: SIGRTMIN+3
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: ubuntu-controller
    image: znerolmolecule/molecule-prebuilt:ubuntu-systemd
    override_command: no
    tty: yes
    capabilities:
      - SYS_ADMIN
    networks:
      - name: molecule-certhub
    groups:
      - controller
    security_opts:
      - seccomp=unconfined
    stop-signal: SIGRTMIN+3
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: centos-controller
    image: znerolmolecule/molecule-prebuilt:centos-systemd
    override_command: no
    tty: yes
    capabilities:
      - SYS_ADMIN
    networks:
      - name: molecule-certhub
    groups:
      - controller
    security_opts:
      - seccomp=unconfined
    stop-signal: SIGRTMIN+3
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: challtestsrv
    image: letsencrypt/pebble-challtestsrv
    command: /usr/bin/pebble-challtestsrv
    networks:
      - name: molecule-certhub

  - name: pebble
    image: letsencrypt/pebble:v1.0.1
    command: >
        /bin/sh -c
        "
        NSENTRY=$$(getent hosts acmens) &&
        exec /usr/bin/pebble
        -config /test/config/pebble-config.json
        -dnsserver $${NSENTRY%% *}:8053
        "
    networks:
      - name: molecule-certhub
        links:
          - challtestsrv:acmens

provisioner:
  name: ansible
  inventory:
    host_vars:
      debian-node:
        molecule_certhub_controller: debian-controller
      ubuntu-node:
        molecule_certhub_controller: ubuntu-controller
      centos-node:
        molecule_certhub_controller: centos-controller
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  lint:
    name: flake8
