---
- name: General Setup
  hosts: controller:server
  tasks:
    - name: Git and OpenSSL present
      become: yes
      become_user: root
      loop:
        - git
        - openssl
        - rsync
      package:
        name: "{{ item }}"
        state: present

    - import_role:
        name: sudo-secure-path

    - import_role:
        name: ansible-role-certhub


- name: Controller Setup
  hosts: controller
  tasks:
    - import_role:
        name: certbot

    - import_role:
        name: sshkey

    - import_role:
        name: pebble-ca

    - import_role:
        name: testsrv-hooks

    - import_role:
        name: ansible-role-certhub
        tasks_from: certbot-noroot-config.yml


- name: Server Setup
  hosts: server
  tasks:
    - import_role:
        name: sshserver

    - import_role:
        name: tlsserver

    - name: Repo push units setup
      delegate_to: "{{ molecule_certhub_controller }}"
      import_role:
        name: ansible-role-certhub
        tasks_from: repo-push-units.yml


- name: Certificate Configs
  hosts: server
  tasks:
    - vars:
        certhub_cert_services:
          - nginx
      import_role:
        name: ansible-role-certhub
        tasks_from: cert-export-units.yml

    - name: Certbot run units setup
      delegate_to: "{{ molecule_certhub_controller }}"
      import_role:
        name: ansible-role-certhub
        tasks_from: certbot-run-units.yml

    - name: Certbot config installed
      delegate_to: "{{ molecule_certhub_controller }}"
      become: yes
      become_user: root
      copy:
        dest: "{{ certhub_cert_certbot_ini_path }}"
        content: |
          server=https://pebble:14000/dir
          agree-tos=true
          register-unsafely-without-email=true
          manual-public-ip-logging-ok=true
          preferred-challenges=dns
          manual=true
          manual-auth-hook=/usr/local/lib/certhub/certbot-hooks/testsrv-dns-01-auth
          manual-cleanup-hook=/usr/local/lib/certhub/certbot-hooks/testsrv-dns-01-cleanup
