---
- name: Converge
  hosts: controller:server
  tasks:
    - name: Git and OpenSSL present
      loop:
        - git
        - openssl
      package:
        name: "{{ item }}"
        state: present

    - import_role:
        name: ansible-role-certhub


- name: Controller
  hosts: controller
  tasks:
    - import_role:
        name: certbot

    - import_role:
        name: sshkey

    - import_role:
        name: pebble-ca

    - import_role:
        name: ansible-role-certhub
        tasks_from: certbot-noroot-config.yml


- name: Server
  hosts: server
  tasks:
    - import_role:
        name: sshserver

    - import_role:
        name: tlsserver
