---
- name: SSH Server setup
  become: yes
  become_user: root
  block:
    - name: SSH Server present
      loop:
        - openssh-server
      package:
        name: "{{ item }}"
        state: present

    - name: SSH Server started
      service:
        name: "{{ 'sshd' if ansible_pkg_mgr == 'dnf' else 'ssh' }}"
        state: started
