- name: TLS Server setup
  become: yes
  become_user: root
  vars:
    tls_key_path: "/etc/certhub/{{ inventory_hostname }}.key.pem"
    tls_csr_path: "/etc/certhub/{{ inventory_hostname }}.csr.pem"
  block:
    - name: TLS Key present
      command: >
        openssl genpkey
        -out "{{ tls_key_path }}"
        -algorithm RSA
        -pkeyopt rsa_keygen_bits:2048
      args:
        creates: "{{ tls_key_path }}"

    - name: TLS Cert request generated
      register: cert_csr
      changed_when: no
      check_mode: no
      command: >
        openssl req -new -batch
        -key "{{ tls_key_path }}"
        -subj "/CN={{ inventory_hostname }}"

    - name: TLS Cert request stored on controller
      loop: "{{ query('inventory_hostnames', 'controller') }}"
      delegate_to: "{{ item }}"
      copy:
        dest: "{{ tls_csr_path }}"
        content: "{{ cert_csr.stdout }}"
