---
- name: Lego downloaded
  become: true
  become_user: certhub
  ansible.builtin.get_url:
    dest: /var/lib/certhub/private/lego_v4.35.2_linux_amd64.tar.gz
    url: https://github.com/go-acme/lego/releases/download/v4.35.2/lego_v4.35.2_linux_amd64.tar.gz
    checksum: sha256:ee5be4bf457de8e3efa86a51651c75c87f0ee0e4e9f3ae14f6034d68365770f3
    owner: certhub
    group: certhub
    mode: "0644"

- name: Lego unarchived
  become: true
  become_user: root
  ansible.builtin.unarchive:
    src: /var/lib/certhub/private/lego_v4.35.2_linux_amd64.tar.gz
    dest: /usr/local/bin/
    creates: /usr/local/bin/lego
    remote_src: true
    extra_opts: [lego]

- name: Lego present
  become: true
  become_user: root
  ansible.builtin.file:
    path: /usr/local/bin/lego
    state: file
    owner: root
    group: root
    mode: "0755"
