---
- name: Local binaries allowed in sudo
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "Defaults\tsecure_path=\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\""
    state: present
    regexp: ^Defaults\s+secure_path\s*=
    insertbefore: BOF
