---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop

env:
  ANSIBLE_PIPELINING: "yes"
  ANSIBLE_FORKS: "16"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ansible ansible-lint yamllint flake8
        run: pip install ansible==7.* ansible-lint==5.* yamllint flake8

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        run: ansible-lint -v .

      - name: Run flake8
        run: flake8

  integration:
    name: Integration Test
    runs-on: ubuntu-latest

    needs:
      - lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install molecule docker
        run: pip install 'ansible==7.*' 'molecule==5.*' 'molecule-plugins[podman]' pytest-testinfra

      - name: Patch crun
        run: |
          curl -fsSL -o crun https://github.com/containers/crun/releases/download/1.14.4/crun-1.14.4-linux-amd64
          sudo install -m 0755 -o root -g root crun /usr/bin/crun

      - name: Run molecule
        run: |
          sudo podman info
          export MOLECULE="$(command -v molecule)" && sudo ${MOLECULE} test

  galaxy:
    name: Ansible Galaxy Import
    runs-on: ubuntu-latest

    needs:
      - integration

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ansible Galaxy Token
        env:
          ANSIBLE_GALAXY_TOKEN: "${{ secrets.ANSIBLE_GALAXY_TOKEN }}"
        run: .github/scripts/setup-galaxy-token.sh

      - name: Trigger Ansible Galaxy Import
        run: ansible-galaxy role import --role-name znerol.certhub znerol ansible-role-certhub
