---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - main
      - develop

env:
  ANSIBLE_PIPELINING: "yes"
  ANSIBLE_FORKS: "16"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ansible ansible-lint yamllint flake8
        run: sudo pipx inject --include-apps --include-deps ansible-base ansible-lint yamllint flake8

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        run: ansible-lint -v .

      - name: Run flake8
        run: flake8

  integration:
    name: Integration Test
    runs-on: ubuntu-latest

    needs:
      - lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install molecule docker
        run: sudo pipx inject --include-apps --include-deps ansible-base 'molecule[docker]' pytest-testinfra

      - name: Run molecule
        run: molecule test

  galaxy:
    name: Ansible Galaxy Import
    runs-on: ubuntu-latest

    needs:
      - integration

    steps:
      - name: Setup Ansible Galaxy Token
        env:
          ANSIBLE_GALAXY_TOKEN: "${{ secrets.ANSIBLE_GALAXY_TOKEN }}"
        run: .github/scripts/setup-galaxy-token.sh

      - name: Trigger Ansible Galaxy Import
        run: ansible-galaxy role import --role-name znerol.certhub znerol ansible-role-certhub
